dnd-side-project/dnd-11th-6-frontend

src/app/meeting/[meetingId]/MeetingPageClient.tsx
MeetingPageClient 컴포넌트에 있는 몇가지 문제들을 수정했습니다.
- 이전 PR 를 병합하다가 생긴 conflict 를 해결하면서 태그가 누락되어 오류가 발생하였고, 코드 수정으로 해결하였습니다.
- mission 오타를 수정했습니다.
- import 순서 규칙에 따라 정렬하여 일관성을 유지했습니다.
=> fix: MeetingPageClient 컴포넌트 오류, 오타 수정

package.json
- package.json 의 dev 스크립트에 -H 0.0.0.0 추가
- 개발 시 로컬 개발 서버를 모든 네트워크 인터페이스에서 접근 가능하도록 추가했습니다
=> chore: 로컬 개발 서버 접근 가능

.eslintrc.json, package.json, scripts/dev.js
- 로컬 개발 환경을 위한 dev.js 파일 작성
- root 의 scripts/dev.js 에 추가했습니다.
=> chore: dev.js 파일 추가

src/app/layout.tsx
- root layout.tsx 의 css 를 변경했습니다.
- items-center 속성은 제거하는 대신에 justify-center 속성은 남겨두었습니다.
- 이미 pretendard 폰트가 적용되어 있어서 불필요한 inter 폰트 적용 코드를 제거했습니다.
- overflow-y-auto 는 전역적으로 적용되는 것보다 필요한 특정 컴포넌트에만 적용되는게 더 나을 것 같아 추가하지 않았습니다.
- 검토 부탁드립니다!
=> fix: root layout css 변경

.storybook/main.ts
- storybook main 파일에 auto docs 를 추가했습니다.
- auto docs 에서 show code 기능을 지원해서 추가했습니다.
=> chore: storybook auto docs 추가

src/components/Button/index.tsx, src/components/Popup/index.stories.tsx, src/components/Popup/index.tsx
#46 
- Popup 컴포넌트를 구현하였습니다.
- storybook 파일을 추가했습니다.
- Button 컴포넌트의 fullWidth 속성을 width 100% 으로 수정했습니다.
- 미션 삭제 확인 팝업 구현 시 사용할 예정입니다.
=> feat: popup 컴포넌트 구현

src/apis/queries/missionQuries.ts, src/app/create-mission/page.tsx, src/app/meeting/photo-capture/_components/PhotoView.tsx, src/stores/useMissionStore.ts
- create-mission 페이지(미션 선택 페이지)에서 랜덤 미션과 모임 미션을 선택할 수 있는 기능을 구현했습니다.
=> feat: 미션 선택하기 기능 구현

src/components/ToogleSwitch/index.tsx
#64 
- 토글 스위치 아이콘 위치가 깨진채로 나와서 코드를 수정했습니다.
=> fix: 아이콘 위치 조정

src/app/entry-meeting/_components/NicknameInput.tsx
#66 
중복되는 닉네임 입력 시 발생하던 메세지 버그를 수정했습니다.
=> fix: password input 메세지 버그 수정

public/icons/alert-circle.svg, src/app/entry-meeting/_components/LinkInput.tsx, src/app/meeting/info/_components/MeetingDetail.tsx, src/app/meeting/photo-capture/_utils/base64ToFile.ts, src/app/meeting/photo-capture/_utils/formatCaptureTime.ts, src/app/meeting/photo/[photoId]/formatCaptureTime.ts, src/components/Callout/index.stories.tsx, src/components/Callout/index.tsx, src/components/QRPopup/index.tsx, src/components/Toast/index.stories.tsx, src/components/Toast/index.tsx
#57 
토스트 메세지를 위한 컴포넌트를 구현했습니다.
=> feat: 토스트 컴포넌트 구현

src/app/create-meeting/_components/MeetingTheme.tsx, src/components/ColorPicker/index.stories.tsx, src/components/ColorPicker/index.tsx
#95
- colorPicker 부분을 재사용하기 위해서 컴포넌트로 분리했습니다
- 스토리북 만들었습니다
=> feat : ColorPicker 컴포넌트 생성

src/app/create-meeting/_components/MeetingDate.tsx, src/app/create-meeting/_components/MeetingLayout.tsx, src/app/create-meeting/_components/MeetingPassword.tsx, src/app/create-meeting/_components/Page.tsx
#98 버그 수정하고 리팩토링했습니다
- layout 수정
=> bug : #98 버그 수정 및 리팩토링

public/icons/CloseSvg.tsx, public/icons/close.svg, src/app/create-meeting/_components/Page.tsx, src/app/entry-meeting/_components/Welcome.tsx, src/app/manage-mission/_components/NewMission.tsx, src/app/meeting/photo-capture/_components/CameraView.tsx, src/app/meeting/photo-capture/_components/PhotoView.tsx, src/app/meeting/photo/[photoId]/page.tsx, src/components/Popup/index.stories.tsx, src/components/Popup/index.tsx, src/components/QRPopup/index.tsx
#56 
- Popup 컴포넌트에 close 버튼을 추가했습니다.
- close svg 의 색상을 커스텀 가능하도록 tsx component 로 변환했습니다.
- 재로그인 팝업 컴포넌트를 구현하려면 close 버튼이 추가로 필요해서 구현했습니다.
- 수정한 Popup 컴포넌트 활용해서 재로그인 할 수 있는 기능 이어서 추가하면 될 것 같습니다.
=> feat: Popup 컴포넌트에 close 버튼 속성 추가

next.config.mjs, src/app/meeting-home/_components/MeetingHeader.tsx, src/app/meeting-home/_components/MeetingPhotoGrid.tsx, src/constant/base_url.ts
#103 
- 기본 상수값 사용
- 상수값 도메인 주소 변경
=> fix : 도메인 주소 상수값으로 변경

src/app/meeting/photo-capture/_components/CameraView.tsx, src/app/meeting/photo-capture/_components/PhotoView.tsx, src/hooks/useCamera.ts
#115 
- 흐릿하게 저장되는 이미지의 화질을 개선하였습니다.
- 파일 크기와 명확한 품질 설정을 위해 이미지 형식을 png 에서 jpeg 로 변경하였습니다.
=> refactor: dpr 적용으로 사진 화질 개선

src/app/create-meeting/_hooks/useMeetingForm.ts
=> hotfix : dayjs 날짜 입력값 format 수정

src/app/manage-mission/_components/NewMission.tsx
- 새로운 미션 생성시 text input 의 place holder 내용을 수정
- 제한 글자수 20자에서 15자로 변경
=> fix: 새 미션 text input place holder 수정 및 제한 글자수 변경

src/app/meeting/info/_components/MeetingDetail.tsx, src/app/meeting/info/_components/MeetingRaising.tsx, src/app/meeting/info/page.tsx, src/components/Inputs/TextInput/index.tsx, src/components/Inputs/__tests__/TextInput.test.tsx, src/components/QRPopup/index.tsx
- 모임 상세 페이지에서 모임 썸네일 이미지 렌더링
- 모임 상세 페이지의 모임 시작, 종료일시를 YYYY.MM.DD AM/PM HH:MM 형식으로 포맷팅
- 배경색 적용을 위한 QR 컴포넌트 수정
- 모임 상세 페이지 전체적인 모임 대표 컬러 적용
=> fix: 모임 상세 페이지 수정

src/apis/meetingApi.ts, src/app/create-meeting/_components/MeetingDate.tsx, src/app/create-meeting/_hooks/useMeetingForm.ts, src/components/Inputs/DateInput/index.tsx
=> fix : #128

.eslintrc.json, src/apis/PasswordPopup.tsx, src/apis/apiUtils.ts, src/apis/queries/meetingQueries.ts, src/apis/queries/participantsQueries.ts, src/app/api/check-previous-user/route.ts, src/app/entry-meeting/_components/MeetingInfo.tsx, src/components/Popup/index.tsx, src/hooks/usePreviousUser.ts, src/stores/useMeetingStore.ts, src/stores/usePasswordPopupStore.ts, src/stores/useUserStore.ts
- sessionStorage 방식에서 localStorage 저장 방식으로 수정했습니다.
- 재진입 유저를 구분하여 로직을 구성했습니다.
- 이전에 접속했던 모임에 다시 접속하면, 이전에 로그인했던 계정으로 재진입이 가능합니다.
=> fix: 접속했던 모임의 재진입 문제 
